---
- name: "[Play 1] Get IP"
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    phpipam_subnet:
    short_hostname:
    domain:

  tasks:
  - name: Include secrets to be used
    no_log: true
    include_vars: secrets.yml

  - include_role:
      name: ansible-role-phpipam-get-ip
    vars:
      phpipam_hostname: "{{ short_hostname + '.' + domain }}"

  - name: "Pass variables to Tower Workflows"
    set_stats:
      data:
        phpipam_ip:  "{{ phpipam_ip }}"

  - name: Setup in-memory inventory for just created VM
    add_host:
      name: "{{ phpipam_ip }}"
      groups: just_created_vms
