---
- name: "[Play 3] Install and configure gluster"
  hosts: all
  vars:
    repos:
      - rhel-7-server-rpms
      - rh-gluster-3-for-rhel-7-server-rpms
      - rh-gluster-3-nfs-for-rhel-7-server-rpms
      - rhel-ha-for-rhel-7-server-rpms

  tasks:
  - name: Disable all RHSM repositories
    rhsm_repository:
      name: '*'
      state: disabled

  - name: Enable all needed repositories.
    rhsm_repository:
      name: "{{ item }}"
      state: enabled
    with_items: "{{ repos }}"

  - name: Install Red Hat Gluster Storage
    package:
      name: redhat-storage-server
      state: present

  - import_role:
      name: gluster.infra
    vars:
      # Firewall setup
      gluster_infra_fw_ports:
        - 2049/tcp
        - 54321/tcp
        - 5900/tcp
        - 5900-6923/tcp
        - 5666/tcp
        - 16514/tcp
      gluster_infra_fw_services:
        - glusterfs

      # Set a disk type, Options: JBOD, RAID6, RAID10
      gluster_infra_disktype: JBOD

      # RAID6 and RAID10 diskcount (Needed only when disktype is raid)
      gluster_infra_diskcount:
      # Stripe unit size always in KiB
      gluster_infra_stripe_unit_size:

      # Variables for creating volume group
      gluster_infra_volume_groups:
        - { vgname: 'gluster_vg1', pvname: '/dev/sdb' }

      # Create thinpools
      gluster_infra_thinpools:
        #- {vgname: 'gluster_vg1', thinpoolname: 'lvthinpool', thinpoolsize: '82G', poolmetadatasize: '16G'}
        - {vgname: 'gluster_vg1', thinpoolname: 'lvthinpool', poolmetadatasize: '16G'}

      # Create a thin volume
      gluster_infra_lv_logicalvols:
        - { vgname: 'gluster_vg1', thinpool: 'lvthinpool', lvname: 'gluster_vg1_thinlv', lvsize: '100G' }

      # Mount the devices
      gluster_infra_mount_devices:
        - { path: '/gluster_bricks/gluster_vg1_thinlv', vgname: 'gluster_vg1', lvname: 'gluster_vg1_thinlv' }
