---
- name: Enroll host to IdM
  hosts: all
  remote_user: root
  vars:

  tasks:
  - name: Include secrets
    no_log: true
    include_vars: secrets.yml

  - include_role:
      name: ansible-role-ipa-client
