---
- name: "Break it for insights to fix :)"
  hosts: all
  become: true

  tasks:
  - name: downgrade openssh
    shell: yum -y downgrade openssh-6.6.1p1-11.el7 openssh-clients-6.6.1p1-11.el7 openssh-server-6.6.1p1-11.el7

  - name: set ChallengeResponseAuthentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      line: "ChallengeResponseAuthentication no"
      regexp: ^\s*ChallengeResponseAuthentication\s
      state: present
      insertafter: "#ChallengeResponseAuthentication"

  - name: set KbdInteractiveAuthentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      line: "KbdInteractiveAuthentication yes"
      regexp: ^\s*KbdInteractiveAuthentication\s
      state: present
      insertafter: "#ChallengeResponseAuthentication"

  - name: restart sshd
    service: name=sshd state=restarted

- name: bash_injection
  hosts: all
  become: true
  vars:
    affected_version:
      '5': 'bash-3.2-33.el5.1'
      '6': 'bash-4.1.2-15.el6_5.1'
      '7': 'bash-4.2.45-5.el7_0.2'

  tasks:
  - name: Downgrade bash to affected version
    command: yum -y downgrade {{affected_version[ansible_distribution_major_version]}}

  - name: Execute insights
    command: "redhat-access-insights"
