---
- name: Satellite Kickstart Post provisioning tasks
  hosts: all
  remote_user: root
  vars:

  tasks:
  - name: Include secrets
    no_log: true
    include_vars: secrets.yml

  - include_role:
      name: ansible-role-ovirt-guest
