---
- name: "[Play 1] Gather standard info from Gluster nodes"
  hosts: all
  gather_facts: true

  tasks:
  - name: Include secrets to be used
    no_log: true
    include_vars: secrets.yml
      
  - name: Get gluster peer status
    command: gluster peer status
    register: gpstatus
    
  - name: Print gluster peer status
    debug:
      msg: {{ gpstatus.stdout }}
      
  - name: Get gluster volumes
    command: gluster volume list
    register: gvlist
    
  - name: Print gluster volumes
    debug:
      msg: {{ gvlist.stdout }} 
      
  - name: Get gluster volumes status
    command: gluster volume status
    register: gvstatus
    
  - name: Print gluster volumes status
    debug:
      msg: {{ gvstatus.stdout }}     