---
- name: "[Play 1] Gather standard info from Gluster nodes"
  hosts: all
  gather_facts: true
  become: yes

  tasks:
  - name: Get gluster peer status
    command: gluster peer status
    register: gpstatus
    
  - name: Print gluster peer status
    debug:
      msg: "{{ gpstatus.stdout }}"
      
  - name: Get gluster volumes
    command: gluster volume list
    register: gvlist
    
  - name: Print gluster volumes
    debug:
      msg: "{{ gvlist.stdout }}"
      
  - name: Get gluster volumes status
    command: gluster volume status
    register: gvstatus
    
  - name: Print gluster volumes status
    debug:
      msg: "{{ gvstatus.stdout }}"   
