- src: git@gitlab.labrats.se:internal-ansible-galaxy/ansible-role-resolv-conf.git
  scm: git
  version: 1.0.0
- src: git@gitlab.labrats.se:internal-ansible-galaxy/ansible-role-date-time.git
  scm: git
  version: 1.0.0
- src: git@gitlab.labrats.se:internal-ansible-galaxy/ansible-role-phpipam-get-ip.git
  scm: git
  version: 1.0.0
- src: git@gitlab.labrats.se:internal-ansible-galaxy/ansible-role-rhv-vm.git
  scm: git
  version: 1.0.0
- src: git@gitlab.labrats.se:internal-ansible-galaxy/ansible-role-satellite-bootstrap.git
  scm: git
  version: 1.0.0
- src: git@gitlab.labrats.se:internal-ansible-galaxy/ansible-role-ipa-client.git
  scm: git
- src: git@gitlab.labrats.se:internal-ansible-galaxy/ansible-role-nagios-nrpe.git
  scm: git
- src: git@gitlab.labrats.se:internal-ansible-galaxy/ansible-role-nagios-bootstrap.git
  scm: git
- src: git@gitlab.labrats.se:internal-ansible-galaxy/ansible-role-ovirt-guest.git
  scm: git
